Make lmfit and pyqtgraph dependencies optional
All extras can be installed via `pip install 'spinmob[fit,GUI]'`

If a user tries to use an optional feature without the appropriate
dependency installed, they will get clear traceback messages like

```bash
$ python -c 'from spinmob import lm_fitter_concept'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ganden/.pyenv/versions/spinmob/lib/python3.8/site-packages/spinmob/lm_fitter_concept.py", line 17, in <module>
    from lmfit import Parameters, minimize, report_fit
ModuleNotFoundError: No module named 'lmfit'
```

or

```bash
$ python -c 'import spinmob; print(spinmob._dialogs.load())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ganden/.pyenv/versions/spinmob/lib/python3.8/site-packages/spinmob/_dialogs.py", line 97, in load
    result = _qtw.QFileDialog.getOpenFileName(None,text,default,filters)
AttributeError: type object '_ModuleNotFound_pyqtgraph' has no attribute 'QFileDialog'
```

Using classes like _ModuleNotFound_pyqtgraph is a hacky way to get clear
error messages for `import spinmob as _s; _qtw = _s._qtw`. However, this
'hack' is needed to work around the primary issue, which is importing
optional dependencies in spinmob/__init__.py. Fixing this the proper way
would require a larger refactor, so I've just used the 'hack' instead
for now.